### ISSUE TITLE
Question about direct effect.

### ISSUE THREAD

**Issue by simpleshinobu** [sebastianGehrmann/CausalMediationAnalysis#1]
When you intervene a middle neuron, how do you process the following neurons effected by this one. If there is no direct path from this neuron to the final prediction, what is the direct effect for this middle neuron? Thank you!

**Comment by boknilev** [comment]
Thanks for the question. When we intervene on a neuron, the direct effect is what does not go through this neuron, but instead flows directly to the response variable.

**Comment by simpleshinobu** [comment]
Thank you for your reply. Do you mean the directed effect is not generated from that neuron, though it is related to the neuron. When the data flow through the neuron, then there is an indirected effect related to the neuron, and when the neuron is skipped, the effect becomes direct effect.

**Comment by boknilev** [comment]
Yes. To put it differently, the total effect has two options, either it goes through a mediator (say, neuron) or not. If it goes through the mediator, we call it the indirect effect. If it doesn't go through the mediator, we call it a direct effect. Of course, usually, we have both direct and indirect effects.

**Comment by simpleshinobu** [comment]
Thank you for your elaborate explanation.
