### ISSUE TITLE
Didn't find code for BERT

### ISSUE THREAD

**Issue by yifei1349** [sebastianGehrmann/CausalMediationAnalysis#4]
Hello!

I carefully read your paper and code, it is really interesting!
But in your code, I just find that for GPT. In your paper, you mentioned Bert and other models.
Is that because I didn't find them in your code? Or you didn't published them in Github?

Best wishes!

**Comment by boknilev** [comment]
Hi, thanks for your interest!

The additional model support is found in this pull request, which hasn’t been merged yet: https://github.com/sebastianGehrmann/CausalMediationAnalysis/pull/2
You can grab them from there.

**Comment by yifei1349** [comment]
It is great thanks for you!
